"""empty message

Revision ID: 2218c6305ae0
Revises: b9fe0876a792
Create Date: 2019-01-23 14:35:03.381251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2218c6305ae0'
down_revision = 'b9fe0876a792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_submission', sa.Column('associate_editor', sa.Integer(), nullable=True))
    op.add_column('new_submission', sa.Column('editor_in_chief_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'new_submission', 'users', ['editor_in_chief_id'], ['id'])
    op.create_foreign_key(None, 'new_submission', 'users', ['associate_editor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'new_submission', type_='foreignkey')
    op.drop_constraint(None, 'new_submission', type_='foreignkey')
    op.drop_column('new_submission', 'editor_in_chief_id')
    op.drop_column('new_submission', 'associate_editor')
    # ### end Alembic commands ###
