"""empty message

Revision ID: 77537f895e13
Revises: 
Create Date: 2019-01-21 16:01:50.019292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77537f895e13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_reviewer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_reviewer', mysql.VARCHAR(length=16), nullable=False))
    # ### end Alembic commands ###
