"""add table article_type

Revision ID: b9fe0876a792
Revises: 
Create Date: 2019-01-23 11:11:42.433156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fe0876a792'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_submission', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'new_submission', 'article_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'new_submission', type_='foreignkey')
    op.drop_column('new_submission', 'type_id')
    # ### end Alembic commands ###
